FIRST AND LAST ARE ECHANGED ? EG NYTHOP
ACCEPT A FILE NAME FROM USER AN DPRINT EXTENTION OF THAT ?
CREATE A LIST OF COLORS FROM , SEPRATED COLOR NAME ENTER BUY USER ?DISPLAY FIRST AND LAST COLOR ?
PRINNT OUT ALL COLOR FRIOM COLOR LIST TO ONE NOT CONTAIN LAST ONE
SORT DISNARY IN ASANDING AND DESENDING ODER
MERGE TW DESNARY ?

